### ISSUE TITLE
Is Socialite-BattleNet extending Socialite correctly?

### ISSUE THREAD

**Issue by CptChaos** [teamreflex/Socialite-BattleNet#2]
I am trying to install Socialite-BattleNet in my Laravel 5.3 install, but I can't seem to get it to work.
The error I get is that the Driver 'BattleNet' is not supported.

I've done some trying myself, but can't seem to get it to work. When I Google the error, it says that the provider should be added as a driver as well, but I can't seem to find the correct files to do that in.

Maybe I am doing something wrong, in that case I would like to know what I am doing wrong, I already have added the serverprovider and the facade to the correct places in the configurations. I also have added three lines to the .env file with my keys and the callback URL.

Versions I am using:
```
"name": "laravel/socialite",
"version": "v2.0.18",

"name": "socialiteproviders/manager",
"version": "v2.1.8",

"name": "team-reflex/socialite-battlenet",
"version": "v1.0.1",
```

**Comment by xKairu** [comment]
Pretty sure you're not supposed to use laravel/socialite, as socialiteproviders essentially overrides it.

**Comment by CptChaos** [comment]
From the Packagist-page:

> README
> BattleNet provider for Laravel Socialite/Socialite Providers.

> Required
> socialiteproviders/manager: ~2.0

And that package is also installed, because this package requires it. So the requirements are met, yet the package says that driver [battlenet] isn't support.

**Comment by xKairu** [comment]
True. When are you getting the error? When trying to use your endpoint or during bootstrap?

**Comment by CptChaos** [comment]
I tried the example code (after installing the service provider and the facade) directly in a route, to test it works:

```
Route::get('/', function () {
    return BattleNet::redirect('eu');
});
```

**Comment by xKairu** [comment]
Are you sure you have the handler in the Socialite handler array?

`'Reflex\SocialiteProviders\BattleNet\BattleNetExtendSocialite@handle',`

**Comment by CptChaos** [comment]
I just added
```
        'SocialiteProviders\Manager\SocialiteWasCalled' => [
            'Reflex\SocialiteProviders\BattleNet\BattleNetExtendSocialite@handle',
        ],
```
To the EventServiceProvider.php file. Wasn't aware it had to be added there instead of the normal serviceproviders. I also can't test it just yet, as I am not at home, where my development environment is.

**Comment by xKairu** [comment]
You should be good to go now that's added in.

**Comment by CptChaos** [comment]
Just tested, it seems to be working in my dev environment indeed! Thanks for the support!
