### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by jcw21396** [teamreflex/Socialite-BattleNet#4]
So I've spent the past four to five hours trying to work with this, and I've had no luck.

I've followed the steps as required, and it takes me to the page, but then I get an OAuth Error. The callback URL isn't even being called, as this is all that is returned.

```
400

Invalid grant type or callback URL is not valid.
```

It's very possible I may be messing something up along the way, but I've redone Socialite as well as this multiple times with the same result.

```
public function login() {
	return \BattleNet::redirect();
}
```

Is all I'm calling to redirect. I can assure that my .env is setup properly.

**App - Providers**

```
// Other service providers
\SocialiteProviders\Manager\ServiceProvider::class,
Reflex\SocialiteProviders\BattleNet\BattleNetServiceProvider::class,
```

**App - Aliases**

```
'BattleNet' => Reflex\SocialiteProviders\BattleNet\BattleNetFacade::class,
'Socialite' => Laravel\Socialite\Facades\Socialite::class,
```

**EventServiceProvider**

```
\SocialiteProviders\Manager\SocialiteWasCalled::class => [
	// add your listeners (aka providers) here
	'Reflex\SocialiteProviders\BattleNet\BattleNetExtendSocialite@handle',
],
```

And finally, my **composer.json**

```
"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/socialite": "^3.0",
        "laravel/tinker": "~1.0",
        "team-reflex/socialite-battlenet": "^1.0"
    },
```

If I'm missing something obvious please point it out.

**Comment by xKairu** [comment]
```
400

Invalid grant type or callback URL is not valid.
```

Are you getting this as an exception on your end, or is it showing on a page on the Battle.net end?

I'm thinking it's one of two things:

1) You've misconfigured your callback URL in your OAuth application settings within the Battle.net dev panel

2) It has to do with the recent rebranding of Battle.net to just "Blizzard".

I'm currently using this in production and it still works.

**Comment by jcw21396** [comment]
Issue was not with this repo in particular, turns out my server was having issues with the URL matching between the .env as well as the Blizzard CP.

You're right when it comes to the rebranding specifically.
